version: "3.9"

services:
  httpbin:
    image: mccutchen/go-httpbin:latest
    container_name: httpbin
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/get"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  tests:
    build: .
    container_name: pytest-runner
    depends_on:
      httpbin:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./reports:/reports
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command: pytest -v --alluredir=/reports

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin